stages:
  - test
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker info

test:
  stage: test
  image: python:3.12
  script:
    - pip install -r requirements.txt
    - python manage.py test
  artifacts:
    when: always
    paths:
      - test-reports/
    reports:
      junit: test-reports/*.xml

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build
    - docker-compose push
  only:
    - main

deploy:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq openssh-client rsync
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - ssh $SSH_USER@$SERVER_IP "
        cd $PROJECT_DIR &&
        docker-compose pull &&
        docker-compose down &&
        docker-compose up -d
      "
  only:
    - main